### PR TITLE
StatusAggregator and messages

### PR DESCRIPTION
**Pull request by mhier**
Note: Maybe review per commit will be easier...
Merge by rebase, squashing NOT intended!

### CODE REVIEW

**Review by d-rothe — APPROVED** [review]
Just a comment/question:
For the StatusOutput it will be (almost?) always undesired to have DataValidity=invalid. You ignore the invalid state, this is OK here, but wouldn't it be better not to write invalid in the first place? At least that should be default behavior of StatusOutputs, I believe.

**Comment by mhier** [comment]
> For the StatusOutput it will be (almost?) always undesired to have DataValidity=invalid.

Why?

The justification for the StatusAggregator to ignore the DataValidity of its inputs is that the same information will typically be seen by other means on another input (broken device causes some status to be invalid and the device status to go to faulty).

In case of an StatusOutput, the DataValidity adds the same type of information as for any other data outputs. If its DataValidity is invalid, it means the status is probably outdated or otherwise unreliable. We shouldn't hide the information at that level in my opinion.

**Comment by killenb** [comment]
I just saw that I am too late to the discussion, and I have no objections to merging. But it would be useful to have status outputs which are always valid, even if the inputs of the module are invalid. This should be specifiable when creating the output ('always valid' or 'follows module validity'). There are use cases for both.

**Comment by mhier** [comment]
> I just saw that I am too late to the discussion, and I have no objections to merging. But it would be useful to have status outputs which are always valid, even if the inputs of the module are invalid. This should be specifiable when creating the output ('always valid' or 'follows module validity'). There are use cases for both.

That may be actually true for any type of variable, and we should probably foresee some mechanism for this.

**Pull request merged**
