### PR TITLE
Mac OS compatibility (replaces #261)

### PR DESCRIPTION
**Pull request by mhier**
- Use correct of version pthread_setname_np depending on platform.
- Omit -Wl,--export-dynamic flag on macOS.

### CODE REVIEW

**Comment by mhier** [comment]
@smarsching I cannot put you as a reviewer here. Can you check whether this works now on Mac OS? Thanks!

**Comment by smarsching** [comment]
Thanks for your changes.

I had to make two additional changes in order to make the code compile. As a I cannot push commits to this branch, here are the changes:

First, the problem with accessing protected constructors from `VertexProperties::visitProxy` still existed. Here is a patch that adds the necessary `friend` declarations:

```patch
diff --git a/include/Model.h b/include/Model.h
index 3a47b62..c50a558 100644
--- a/include/Model.h
+++ b/include/Model.h
@@ -193,6 +193,7 @@ namespace ChimeraTK::Model {
     friend class DeviceModuleProxy;
     friend class ProcessVariableProxy;
     friend class DirectoryProxy;
+    friend struct VertexProperties;
 
     /// This constructor creates a new, empty model with the given ModuleGroup as application root.
     explicit RootProxy(ModuleGroup& app);
@@ -256,6 +257,7 @@ namespace ChimeraTK::Model {
     /// Update ModuleGroup reference after move operation
     void informMove(ModuleGroup& group);
     friend class ChimeraTK::ModuleGroup;
+    friend struct VertexProperties;
   };
 
   /********************************************************************************************************************/
@@ -282,6 +284,7 @@ namespace ChimeraTK::Model {
     /// Update ApplicationModule reference after move operation
     void informMove(ApplicationModule& module);
     friend class ChimeraTK::ApplicationModule;
+    friend struct VertexProperties;
   };
 
   /********************************************************************************************************************/
@@ -306,6 +309,7 @@ namespace ChimeraTK::Model {
     /// Update VariableGroup reference after move operation
     void informMove(VariableGroup& group);
     friend class ChimeraTK::VariableGroup;
+    friend struct VertexProperties;
   };
 
   /********************************************************************************************************************/
@@ -327,6 +331,7 @@ namespace ChimeraTK::Model {
     /// Update DeviceModule reference after move operation
     void informMove(DeviceModule& group);
     friend class ChimeraTK::DeviceModule;
+    friend struct VertexProperties;
   };
 
   /********************************************************************************************************************/
@@ -369,6 +374,7 @@ namespace ChimeraTK::Model {
 
     friend class ChimeraTK::VariableNetworkNode;
     friend class ChimeraTK::DeviceModule;
+    friend struct VertexProperties;
 
     template<typename T>
     friend class ChimeraTK::InversionOfControlAccessor;
@@ -400,6 +406,8 @@ namespace ChimeraTK::Model {
     ProcessVariableProxy addVariable(const std::string& name);
     DirectoryProxy addDirectory(const std::string& name);
     DirectoryProxy addDirectoryRecursive(const std::string& name);
+
+    friend struct VertexProperties;
   };
 
   /********************************************************************************************************************/
```

This problem is interesting from a technical perspective: Apparently, GCC thinks that the `friend` declarations in the `Proxy` class are sufficient because the constructors are imported into the child classes with a `using` declaration.

Clang, however, complains that these constructors are `protected` because it considers them part of the child classs. I can’t tell which one of the two is right according to the C++ specification. This might well be an ambiguity in the original specification, though in my opinion the behavior of Clang seems a bit more reasonable.

The other pathc affects the `Utilities.cc` file. As we are using `phthread_setname_np`, the correct header needs to be included:

```patch
diff --git a/src/Utilities.cc b/src/Utilities.cc
index f65e8f7..f8f2098 100644
--- a/src/Utilities.cc
+++ b/src/Utilities.cc
@@ -2,6 +2,12 @@
 // SPDX-License-Identifier: LGPL-3.0-or-later
 #include "Utilities.h"
 
+#if defined(__APPLE__)
+extern "C" {
+#  include <pthread.h>
+} // extern "C"
+#endif // defined(__APPLE__)
+
 namespace ChimeraTK::Utilities {
 
   /********************************************************************************************************************/
```

After applying these two patches on top of your branch, I can build the project without any further problems.

**Comment by mhier** [comment]
Oh interesting. Indeed, the friend definitions should be there since the `using` is in the private section (as it should). I added them, and I also added the missing header file but unconditionally (not sure why it works without on Linux gcc). Do you want to check on last time hopefully? :-)

**Comment by smarsching** [comment]
I tested the version from your branch and it compiles fine now.

**Comment by mhier** [comment]
thanks, merged!

**Pull request merged**
