### PR TITLE
Device support for history

### PR DESCRIPTION
**Pull request by zenker**
This allows to add a **DeviceModule to the ServerHistory** module. For the tests I needed to add a logical name mapping file, which is added also to the test.dmap file. I also need the method **`virtualiseFromCatalog`** from the DeviceModule - so I **made it public**. This is the only way the user can add the device PVs to the HistoryModule. 
Having that method public also allows to connect a **DeviceModule to the MicroDAQ** module.

### CODE REVIEW

**Comment by mhier** [comment]
I don't like the virtualiseFromCatalog() function to be public, because in the long run we want to eliminate that function and find a better solution. If it's public, it might even appear in application code, or module libraries which are not under our control could use it.

Can you please instead solve this problem by making the module a friend of the DeviceModule? It's also not an ideal solution, but at least it contains the problem.

**Comment by zenker** [comment]
In that case I need to add a special `addSource` function for devices and I have to call that function inside my module. This is because this function is to be used by the user:
https://github.com/ChimeraTK/ApplicationCore/blob/882cc191e0cbb710343149a0fa7863919e0c231a/tests/executables_src/testHistory.C#L120

Is this your preferred solution?

**Comment by mhier** [comment]
Ah sorry, I misread the code (looking only at diffs is dangerous ;-)). Yes, in that case please create an overloaded addSource() which accepts a DeviceModule and internally does the virtualiseFromCatalog(). This function should not appear in user code or tests.

**Comment by zenker** [comment]
Done.

**Pull request merged**
